api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.index, name='index'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/new/', views.create, name='create'),
    path('post/new/article/', views.create_article, name='create_article'),
    path('post/new/status/', views.create_status, name='create_status'),
    path('post/compose/', views.compose_status, name='compose_status'),
    path('compose/', views.compose_route, name='compose_route'),
    path('post/new/poll/', views.create_poll, name='create_poll'),
    path('post/<slug:slug>/', views.detail, name='detail'),
    path('post/<slug:slug>/reply/', views.reply_route, name='reply_route'),
    path('post/<slug:slug>/edit/', views.edit, name='edit'),
    path('post/<slug:slug>/delete/', views.delete, name='delete'),
    path('post/<slug:slug>/like-toggle/', views.toggle_like, name='toggle_like'),
    path('post/<slug:slug>/comment/', views.add_comment, name='add_comment'),
    path('post/<slug:slug>/vote/<int:option_id>/', views.vote_poll, name='vote_poll'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from blog.views import home as blog_home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', blog_home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('follows/', include('follows.urls', namespace='follows')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('api/', include('api.urls', namespace='api')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .widgets import CustomCKEditorWidget
from .models import Post, Comment, PollOption


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'type', 'content']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control post-title-input',
                'placeholder': 'Post title',
                'autocomplete': 'off',
            }),
            'content': CustomCKEditorWidget(config_name='default'),
        }


class PollOptionForm(forms.ModelForm):
    class Meta:
        model = PollOption
        fields = ['text']


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control post-title-input',
                'placeholder': 'Article title',
                'autocomplete': 'off',
            }),
            'content': CustomCKEditorWidget(config_name='default'),
        }

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.type = Post.PostType.ARTICLE
        if commit:
            instance.save()
        return instance


class StatusPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 6,
                'placeholder': "What's on your mind?",
            })
        }

    def clean_content(self):
        content = self.cleaned_data.get('content', '').strip()
        if not content:
            raise forms.ValidationError('Content is required.')
        return content

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.type = Post.PostType.POST
        instance.title = instance.title or ''
        if commit:
            instance.save()
        return instance


class PollPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'starts_at', 'ends_at', 'max_choices']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control post-title-input',
                'placeholder': 'Poll question',
                'autocomplete': 'off',
            }),
            'starts_at': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}),
            'ends_at': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}),
        }

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.type = Post.PostType.POLL
        instance.content = ''
        if commit:
            instance.save()
        return instance


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

blog/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseForbidden, HttpResponseNotAllowed, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Post, Comment, PollOption
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import (
    PostForm,
    CommentForm,
    ArticlePostForm,
    StatusPostForm,
    PollPostForm,
)
from follows.models import Follow
from django.db.utils import OperationalError
from django.views.decorators.http import require_POST
from django.template.loader import render_to_string
import json


def index(request: HttpRequest) -> HttpResponse:
    qs = Post.objects.select_related('author').prefetch_related('likes', 'poll_options').all()
    q = request.GET.get('q', '').strip()
    t = request.GET.get('type', '').strip()
    if q:
        qs = qs.filter(title__icontains=q) | qs.filter(content__icontains=q)
    if t in ['article', 'post', 'poll']:
        qs = qs.filter(type=t)
    paginator = Paginator(qs, 15)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/index.html', { 'posts': posts })


def home(request: HttpRequest) -> HttpResponse:
    # Following feed: posts by users current user follows
    posts = Post.objects.select_related('author').prefetch_related('likes')
    if request.user.is_authenticated:
        try:
            following_ids = Follow.objects.filter(follower=request.user).values_list('following_id', flat=True)
            posts = posts.filter(author_id__in=following_ids)
        except OperationalError:
            # Follows table not migrated yet; show empty following feed
            posts = posts.none()
    else:
        posts = posts.none()
    posts = posts[:10]
    return render(request, 'home.html', { 'posts': posts })


@login_required
@require_POST
def compose_status(request: HttpRequest) -> HttpResponse:
    content = request.POST.get('content', '').strip()
    if not content:
        if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return JsonResponse({'ok': False, 'error': 'Say something to post.'}, status=400)
        messages.error(request, 'Say something to post.')
        return redirect('blog:index')
    post = Post(author=request.user, type=Post.PostType.POST, title='', content=content)
    post.save()
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        html = render_to_string('blog/_post_card.html', {'post': post}, request=request)
        return JsonResponse({'ok': True, 'html': html})
    messages.success(request, 'Posted!')
    return redirect('blog:index')


def compose_route(request: HttpRequest) -> HttpResponse:
    # Serves a modal-friendly compose form. If requested via AJAX, return just the modal body.
    if not request.user.is_authenticated:
        if request.headers.get('HX-Request') == 'true' or request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            return HttpResponse(status=403)
        return redirect('accounts:login')
    if request.headers.get('HX-Request') == 'true' or request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        html = render_to_string('blog/_compose_modal_body.html', {}, request=request)
        return HttpResponse(html)
    return render(request, 'blog/compose.html')


def detail(request: HttpRequest, slug: str) -> HttpResponse:
    post = get_object_or_404(Post.objects.select_related('author').prefetch_related('likes', 'comments__author', 'poll_options__voters'), slug=slug)
    comment_form = CommentForm()
    # Build poll context
    options_data = []
    total_votes = 0
    if getattr(post, 'is_poll', False):
        for opt in post.poll_options.all():
            total_votes += opt.votes_count
        user_voted_option_ids = set()
        if request.user.is_authenticated:
            for opt in post.poll_options.all():
                if opt.voters.filter(pk=request.user.pk).exists():
                    user_voted_option_ids.add(opt.pk)
        for opt in post.poll_options.all():
            percent = 0
            if total_votes > 0:
                percent = int(round((opt.votes_count / total_votes) * 100))
            options_data.append({
                'id': opt.pk,
                'text': opt.text,
                'votes': opt.votes_count,
                'percent': percent,
                'selected': opt.pk in user_voted_option_ids,
            })
        return render(request, 'blog/detail.html', {
            'post': post,
            'comment_form': comment_form,
            'poll_total_votes': total_votes,
            'poll_options': options_data,
        })
    return render(request, 'blog/detail.html', { 'post': post, 'comment_form': comment_form })


@login_required
def create(request: HttpRequest) -> HttpResponse:
    return render(request, 'blog/type_select.html')


@login_required
def create_article(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = ArticlePostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, 'Article created!')
            return redirect('blog:detail', slug=post.slug)
    else:
        form = ArticlePostForm()
    return render(request, 'blog/form.html', { 'form': form, 'title': 'Create Article', 'show_poll_fields': False })


@login_required
def create_status(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = StatusPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, 'Post created!')
            return redirect('blog:detail', slug=post.slug)
    else:
        form = StatusPostForm()
    return render(request, 'blog/form.html', { 'form': form, 'title': 'Create Post', 'show_poll_fields': False })


@login_required
def create_poll(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = PollPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            option_texts = [
                request.POST.get('option1', '').strip(),
                request.POST.get('option2', '').strip(),
                request.POST.get('option3', '').strip(),
                request.POST.get('option4', '').strip(),
            ]
            for text in option_texts:
                if text:
                    PollOption.objects.create(post=post, text=text)
            messages.success(request, 'Poll created!')
            return redirect('blog:detail', slug=post.slug)
    else:
        form = PollPostForm()
    return render(request, 'blog/form.html', { 'form': form, 'title': 'Create Poll', 'show_poll_fields': True })


@login_required
def edit(request: HttpRequest, slug: str) -> HttpResponse:
    post = get_object_or_404(Post, slug=slug)
    if post.author != request.user:
        return HttpResponseForbidden('Not allowed')
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            if getattr(post, 'is_poll', False):
                post.poll_options.all().delete()
                option_texts = [
                    request.POST.get('option1', '').strip(),
                    request.POST.get('option2', '').strip(),
                    request.POST.get('option3', '').strip(),
                    request.POST.get('option4', '').strip(),
                ]
                for text in option_texts:
                    if text:
                        PollOption.objects.create(post=post, text=text)
            messages.success(request, 'Post updated!')
            return redirect('blog:detail', slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/form.html', { 'form': form, 'title': 'Edit Post' })


@login_required
def delete(request: HttpRequest, slug: str) -> HttpResponse:
    post = get_object_or_404(Post, slug=slug)
    if post.author != request.user:
        return HttpResponseForbidden('Not allowed')
    if request.method == 'POST':
        post.delete()
        messages.success(request, 'Post deleted!')
        return redirect('blog:index')
    return render(request, 'blog/confirm_delete.html', { 'post': post })


@login_required
def toggle_like(request: HttpRequest, slug: str) -> HttpResponse:
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])
    post = get_object_or_404(Post, slug=slug)
    liked = False
    if request.user in post.likes.all():
        post.likes.remove(request.user)
        liked = False
        messages.info(request, 'Unliked post')
    else:
        post.likes.add(request.user)
        liked = True
        messages.success(request, 'Liked post')
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return JsonResponse({'ok': True, 'liked': liked, 'count': post.likes.count()})
    return redirect('blog:detail', slug=slug)


@login_required
def add_comment(request: HttpRequest, slug: str) -> HttpResponse:
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])
    post = get_object_or_404(Post, slug=slug)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()
        if request.headers.get('HX-Request') == 'true' or request.headers.get('X-Requested-With') == 'XMLHttpRequest':

templates/blog/_compose_modal_body.html
<form id="compose-modal-form" method="post" action="{% url 'blog:compose_status' %}">
  {% csrf_token %}
  <div class="d-flex gap-3">
    <div>
      {% if request.user.profile and request.user.profile.avatar %}
        <img class="avatar" src="{{ request.user.profile.avatar.url }}" alt="avatar">
      {% else %}
        <div class="avatar bg-secondary-subtle"></div>
      {% endif %}
    </div>
    <div class="flex-grow-1">
      <textarea name="content" class="form-control border-0" rows="4" placeholder="What's happening?"></textarea>
      <div class="d-flex justify-content-end mt-3">
        <button type="submit" class="btn btn-brand rounded-pill px-3">Post</button>
      </div>
    </div>
  </div>
</form>
<script>
(function(){
  const form = document.getElementById('compose-modal-form');
  if(!form) return;
  function getCookie(name){
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      const cookies = document.cookie.split(';');
      for (let i = 0; i < cookies.length; i++) {
        const cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  form.addEventListener('submit', async function(e){
    e.preventDefault();
    const textarea = form.querySelector('textarea[name="content"]');
    const content = textarea.value.trim();
    if(!content) return;
    try {
      const res = await fetch(form.action, {
        method: 'POST',
        headers: { 'X-Requested-With':'XMLHttpRequest', 'X-CSRFToken': getCookie('csrftoken'), 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' },
        body: new URLSearchParams({ content })
      });
      if(res.ok){
        const data = await res.json();
        if(data.ok && data.html){
          const feed = document.getElementById('feed-list');
          if(feed){
            const wrap = document.createElement('div');
            wrap.innerHTML = data.html; const node = wrap.firstElementChild; if(node){ feed.prepend(node); }
          }
          const modalEl = document.getElementById('composeModal');
          const instance = bootstrap.Modal.getInstance(modalEl);
          if(instance){ instance.hide(); }
        }
      }
    } catch(err){}
  });
})();
</script>

templates/blog/_reply_modal_body.html
<div class="mb-3">
  {% include 'blog/_post_card.html' with post=post %}
</div>
<form id="reply-modal-form" method="post" action="/blog/post/{{ post.slug }}/comment/" hx-post="/blog/post/{{ post.slug }}/comment/" hx-swap="none" hx-push-url="false">
  {% csrf_token %}
  <input type="hidden" name="next" value="/blog/#post-{{ post.slug }}">
  <div class="d-flex gap-3">
    <div>
      {% if request.user.profile and request.user.profile.avatar %}
        <img class="avatar" src="{{ request.user.profile.avatar.url }}" alt="avatar">
      {% else %}
        <div class="avatar bg-secondary-subtle"></div>
      {% endif %}
    </div>
    <div class="flex-grow-1">
      <textarea name="content" class="form-control border-0 autosize" rows="1" placeholder="Post your reply"></textarea>
      <div class="d-flex justify-content-end mt-3">
        <button type="submit" class="btn btn-brand rounded-pill px-3">Reply</button>
      </div>
    </div>
  </div>
</form>
<script>
(function(){
  const form = document.getElementById('reply-modal-form');
  if(!form) return;
  // Autosize textarea
  const ta = form.querySelector('textarea.autosize');
  if(ta){
    function resize(){ ta.style.height = 'auto'; ta.style.height = Math.min(220, ta.scrollHeight) + 'px'; }
    ta.addEventListener('input', resize); resize();
  }
  document.body.addEventListener('htmx:afterRequest', function(ev){
    if(ev.target === form){
      try {
        const resp = ev.detail.xhr.responseText;
        let data; try { data = JSON.parse(resp); } catch(_){ data = null; }
        if(data && data.ok){
          const card = document.querySelector(`[data-post-slug='{{ post.slug }}']`);
          if(card){
            const countEl = card.querySelector('.comment-count');
            if(countEl){ countEl.textContent = String(parseInt(countEl.textContent||'0',10) + 1); }
          }
          const evt = new Event('reply:success'); document.body.dispatchEvent(evt);
        }
      } catch(err){}
    }
  });
})();
</script>

templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog{% endblock %}
{% block content %}
  <div class="border-bottom p-3 d-flex align-items-center justify-content-between" style="background:#ffffff; position: sticky; top: 0; z-index: 1;">
    <div class="fw-bold">Home</div>
    <div class="text-secondary small">Latest</div>
  </div>

  <div class="p-3" style="background:#ffffff;">
    <form method="get" class="position-relative mb-2" role="search" id="search-form">
      <span class="search-icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
      </span>
      <div class="d-flex gap-2">
        <input type="search" class="form-control search-input" name="q" id="search-input" placeholder="Search" value="{{ request.GET.q }}">
        <select class="form-select" name="type" style="max-width: 160px;">
          <option value="">All</option>
          <option value="article" {% if request.GET.type == 'article' %}selected{% endif %}>Articles</option>
          <option value="post" {% if request.GET.type == 'post' %}selected{% endif %}>Posts</option>
          <option value="poll" {% if request.GET.type == 'poll' %}selected{% endif %}>Polls</option>
        </select>
        <button class="btn btn-soft" type="submit">Filter</button>
      </div>
    </form>

    {% if request.user.is_authenticated %}
      <form class="d-flex gap-3 py-2" method="post" action="{% url 'blog:compose_status' %}" id="composer-form">
        {% csrf_token %}
        <div>
          {% if request.user.profile and request.user.profile.avatar %}
            <img class="avatar" src="{{ request.user.profile.avatar.url }}" alt="avatar">
          {% else %}
            <div class="avatar bg-secondary-subtle"></div>
          {% endif %}
        </div>
        <div class="flex-grow-1">
          <textarea name="content" id="composer-input" class="form-control border-0" style="resize:none; background:transparent;" rows="3" placeholder="What's happening?"></textarea>
          <div class="d-flex align-items-center justify-content-between mt-2">
            <div class="d-flex align-items-center gap-3 text-secondary">
              <button type="button" class="btn tweet-action-btn" title="Media">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg>
              </button>
              <button type="button" class="btn tweet-action-btn" title="GIF">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect><path d="M7 10h3"></path><path d="M14 8v4"></path><path d="M17 8h3"></path></svg>
              </button>
              <button type="button" class="btn tweet-action-btn" title="Poll">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="6" y1="20" x2="6" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="18" y1="20" x2="18" y2="14"></line></svg>
              </button>
              <button type="button" class="btn tweet-action-btn" title="Emoji">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><path d="M8 14s1.5 2 4 2 4-2 4-2"></path><line x1="9" y1="9" x2="9.01" y2="9"></line><line x1="15" y1="9" x2="15.01" y2="9"></line></svg>
              </button>
              <button type="button" class="btn tweet-action-btn" title="Schedule">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
              </button>
              <button type="button" class="btn tweet-action-btn" title="Location">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 10c0 7-9 13-9 13S3 17 3 10a9 9 0 1 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
              </button>
              <button type="button" class="btn tweet-action-btn" title="More">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
              </button>
            </div>
            <button id="composer-post" class="btn btn-brand rounded-pill px-3" disabled>Post</button>
          </div>
        </div>
      </form>
      <div class="border-top mt-2"></div>
    {% endif %}
  </div>
  <div id="feed-list">
  {% for post in posts %}
    {% include 'blog/_post_card.html' with post=post %}
  {% empty %}
    <p class="p-3">No posts yet.</p>
  {% endfor %}
  </div>
  {% if posts.paginator.num_pages > 1 %}
    <nav aria-label="Page navigation" class="bg-white border-top p-3">
      <ul class="pagination justify-content-center mt-2 mb-0">
        {% if posts.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">Previous</span></li>
        {% endif %}

        {% for num in posts.paginator.page_range %}
          {% if num == posts.number %}
            <li class="page-item active" aria-current="page"><span class="page-link">{{ num }}</span></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
          {% endif %}
        {% endfor %}

        {% if posts.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Next</a></li>
        {% else %}
          <li class="page-item disabled"><span class="page-link">Next</span></li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
  <script>
    (function(){
      const input = document.getElementById('search-input');
      const form = document.getElementById('search-form');
      if(!input || !form) return;
      let t=null; input.addEventListener('input', function(){
        clearTimeout(t); t = setTimeout(()=> form.submit(), 400);
      });
    })();
  </script>
  <script>
    (function(){
      const input = document.getElementById('composer-input');
      const btn = document.getElementById('composer-post');
      const form = document.getElementById('composer-form');
      const feed = document.getElementById('feed-list');
      function getCookie(name){
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      function getCookie(name){
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      if(!input || !btn) return;
      function update(){ btn.disabled = input.value.trim().length === 0; }
      input.addEventListener('input', update); update();
      if(form && feed){
        form.addEventListener('submit', async function(e){
          e.preventDefault();
          if(btn.disabled) return;
          btn.disabled = true;
          const content = input.value.trim();
          try{
            const res = await fetch(form.action, {
              method: 'POST',
              headers: { 'X-Requested-With': 'XMLHttpRequest', 'X-CSRFToken': getCookie('csrftoken'), 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' },
              body: new URLSearchParams({ content })
            });
            if(res.ok){
              const data = await res.json();
              if(data.ok && data.html){
                const wrapper = document.createElement('div');
                wrapper.innerHTML = data.html;
                const node = wrapper.firstElementChild;
                if(node){ feed.prepend(node); }
                input.value = '';
                update();
              }
            }
          } catch(err) {
          } finally {
            btn.disabled = input.value.trim().length === 0;
          }
        });
      }

      // Delegate like toggles (no page refresh)
      if(feed){
        feed.addEventListener('click', async function(e){
          const btn = e.target.closest('.like-btn');
          if(!btn) return;
          e.preventDefault();
          const url = btn.getAttribute('data-like-url');
          try{
            const res = await fetch(url, { method:'POST', headers:{ 'X-Requested-With':'XMLHttpRequest', 'X-CSRFToken': getCookie('csrftoken') } });
            if(!res.ok) return;
            const data = await res.json();
            if(!data.ok) return;
            const countEl = btn.querySelector('.like-count');
            if(countEl){ countEl.textContent = data.count; }
          }catch(err){}
        });
      }
    })();
  </script>
{% endblock %}